name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: |
          npm run build
          # Ensure necessary files are copied to dist
          cp public/404.html dist/
          cp public/_redirects dist/
          touch dist/.nojekyll
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          clean-exclude: |
            .git
            .github
            .gitignore
            CNAME
            404.html
            _redirects
          commit-message: 'Deploy: 🚀 Deploying to GitHub Pages'
      
      - name: Verify deployment
        if: success()
        run: |
          echo "Deployment successful!"
          echo "URL: ${{ steps.deployment.outputs.page_url }}"
